batch_mode: false
combined_pdf: true
input_pdf: C:\Users\brian.atkins\OneDrive - Lindamood Demolition\24-105 PHMS NPC -
  Documents\truck tickets\2025-08-09\export\24-105_2025-08-09_class2_podium_WM_124.tif
ocr_engine: doctr
orientation_check: tesseract
output_dir: C:\Users\brian.atkins\OneDrive - Lindamood Demolition\24-105 PHMS NPC
  - Documents\truck tickets\2025-08-09\processed\p1
output_format:
  - csv
  - excel
  - vendor_pdf
run_type: initial
